---
title: "Algorithmer og avancerede konstruktioner"
output: 
    ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Faglige mål
- Forstå og anvende klassiske algorithmer til søgning og sortering
- Forstå rekursion som en styringskonstruktion
- Kende til og implementere enkel træstrukturer (binært søgetræ)
- (Supplerende) Analysere og sammenligne algoirthmers effektivitet. 
- (Supplerende) Arbejde med mere komplekse datastrukturer og bruge dem i problemløsning.

## Indehold


## Materialer
- [Turtle graphics](https://docs.python.org/3/library/turtle.html)
- [Introduction to algrithms, third edition](https://www.cs.mcgill.ca/~akroit/math/compsci/Cormen%20Introduction%20to%20Algorithms.pdf)



## Introduktion
### Hvad er en algoirtme?
" *An **algorithm** is any well-defined computational procedure that takes some value, or set of values, 
as **input** and produce some value, or set of values, as **output**. An algorithm is thus a sequence of computational steps
that transform the input into the output * " 
[Introduction to algrithms, third edition](https://www.cs.mcgill.ca/~akroit/math/compsci/Cormen%20Introduction%20to%20Algorithms.pdf)


## Sorteringsalgorithmer
### Insertion sort
ref: https://www.geeksforgeeks.org/dsa/insertion-sort-algorithm/

```
Insertion_sort(A)
    for j = 2 to A.length
        key = A[j]
        // Insert A[j] into the sorted sequence A[1..j-1]
        i = j-1
        while i>0 and A[i] > key   
            A[i+1] = A[i]
            i=i-1
        A[i+1]=key
```

### Selection sort
ref: https://www.geeksforgeeks.org/dsa/selection-sort-algorithm-2/

Man leder gentagne gange efter det mindste element i den del af listen, der endnu ikke er sorteret, 
og bytter det frem til den korrekte position.

1. Find det mindste element i hele listen, og byt det med elementet på første plads.
2. Find derefter det næstmindste element i resten af listen (fra position 2 til n), og byt det på plads.
3. Fortsæt sådan, indtil alle elementer står i rækkefølge.

### Bubble sort
Man lader de største elementer “boble” op til toppen ved gentagne sammenligninger og bytninger af naboelementer.

1. Sammenlign to naboer. Hvis de står forkert, byt dem.
2. Gå gennem hele listen.
3. Gentag processen, indtil der ikke er flere bytninger.

### Merge sort (divide & conquer)

En rekursiv ”divide and conquer”-algoritme: man deler listen i to halvdele, sorterer hver del, og fletter dem derefter sammen i én sorteret liste.

1. Del listen i to lige store dele.
2. Sortér hver del rekursivt (indtil kun ét element er tilbage).
3. Flet de to sorterede del-lister sammen.



## Hvad koster proceduren?

### The Hiring problem

Forestil dig, at en virksomhed skal ansætte en ny medarbejde ud fra n ansøgere. Kandidaterne ankommer én af gangen,
og virksomhed skal træffe en beslutning med det samme: enten ansætte kandidaten eller afvise dem for altid.

For hver kandidat skal virksomheden:
1. afholde en sametale, som altid koster en fast pris $c_i$.
2. Vurdere kandidaten - er de bedre end den nuværende medarbejder?
3. Hvis ja, fyre den gamle og ansætte den nye, hvilket medfører en ekstra omkostning $c_h$.
De samlede forventede omkostning afhænger af:
- Antal samtaler: $n$
- Antal ansættelse: afhænger af, hvor mange gange en ny "bedre kandidat" dukker op. 

## Binær søgning

- Gæt et tal mellem 1 og 100
- Algoritme

## Rekursion
- n'th Fibonacci 
- n'th factorial 

## Advancered konstruktioner

### Træ 


- node 
- addChild
- displayDescendants



## Opgave

1. Mundtelig Oplæg for et emnet
    - Dijkstra's algoritme
    - Rod cutting problem
    - Activity-selection problem
    - Tower of Hanoi promblem

2. Generative art 

